phrase:
  project_id: phrase-app-project-id-placeholder
  push:
    sources:
    - file: ./_locales/<locale_name>/messages.json
      params:
        file_format: json
  pull:
    targets:
    - file: ./_locales/<locale_name>/messages.json
      params:
        file_format: json
